import { Inter } from 'next/font/google'
import './globals.css'

export const metadata = {
  title: 'Assistante Maternelle',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className='bg-gray-100'>
        <main id="root" className="flex flex-col items-center p-12">
          <div className="relative flex place-items-center">
            <h2 className={`${inter.className} mb-3 text-2xl font-semibold`}>
              Assistante Maternelle
            </h2>
          </div>{children}
        </main>
      </body>
    </html>
  )
}
